### PR TITLE
Complete App

### PR DESCRIPTION
**Pull request by emmyobonyo**
### Tasks Completed
- Added Navigation.
- Added Hero Section.
- Added Picture Section.

### CODE REVIEW

**Review by KnightWorker37 — APPROVED** [review]

**Review by KnightWorker37 — COMMENTED** [review]
It's not responsive. This is what it looks like on  mobile device:
image

**Comment by raybesiga** [comment]
@emmyobonyo can we make this responsive? 😄

**Comment by emmyobonyo** [comment]
@raybesiga Yes we can :)

**Comment by raybesiga** [comment]
> @raybesiga Yes we can :)

Great. How close are we to achieving this? @emmyobonyo

**Comment by emmyobonyo** [comment]
@raybesiga Updated Web App to make it responsive.

**Comment by raybesiga** [comment]
This is what I see.. @emmyobonyo @KnightWorker37 it looks like an unresponsive iframe in a viewport

screencapture-localhost-3000-2022-02-22-17_25_05

Why is the website in a container? And not taking up the viewport?

**Comment by emmyobonyo** [comment]
@raybesiga It's part of the Figma design. Kindly look through the [Figma design](https://www.figma.com/file/35Z4xK9iyTErNYfkenMAhx/Airbnb-Experiences-(Copy))

**Comment by KnightWorker37** [comment]
The responsive design is way way better :+1: @emmyobonyo

**Pull request merged**
